CREATE DATABASE Projeto;

USE Projeto;

CREATE TABLE usuario (
    id INT PRIMARY KEY AUTO_INCREMENT, 
    nome VARCHAR(70) NOT NULL, -- nome do úsuario
    email VARCHAR(60) UNIQUE, -- email para registro/login
    senha VARCHAR(30) NOT NULL,  -- senha para registro/login
    cpf CHAR(11) UNIQUE, -- cpf para identificar o úsuario
    acesso VARCHAR(20) -- Tipos de acesso para o úsuario para separar permissões/conteúdos
    CONSTRAINT chCheck CHECK (acesso IN ('administrador', 'suporte', 'normal', 'cliente')) 
);

CREATE TABLE empresa(
    id INT PRIMARY KEY AUTO_INCREMENT,
    razao_social VARCHAR(70) NOT NULL, -- NOME DA EMPRESA
    cnpj CHAR(14) UNIQUE, -- CNPJ DA EMPRESA, COM FINS DE IDENTIFICAR QUANTOS SENSORES INSTALADOS EM CÂMARAS A EMPRESA TEM E QUANTOS DASHBOARDS VÃO APARECER
    telefone VARCHAR(15) UNIQUE -- TELEFONE DE CONTATO PARA O CNPJ ESPECIFICO, CASO OCORRA ALGUM PROBLEMA COM O SENSOR OU ERRO DE LEVANTAMENTOS DE DADOS
);

CREATE TABLE camara(
    id INT PRIMARY KEY AUTO_INCREMENT,
    identificacao VARCHAR(50) NOT NULL, -- "NOME" DA CÂMARA, PARA CASO HAJA MAIS DE UMA, O FUNCIONÁRIO CONSEGUIR DIFERENCIAR UMA DAS OUTRAS.
    comprimento_metros DECIMAL (4,2), -- COMPRIMENTO EM METROS DA CÂMARA PARA SABER QUANTOS SENSORES POSICIONAR
    temp_minima DECIMAL(4,2) DEFAULT 2.00, -- TEMPERATURA MINÍMA PARA CONTROLE
    temp_maxima DECIMAL(4,2) DEFAULT 8.00, -- TEMPERATURA MÁXIMA PARA CONTROLE
    id_empresa INT -- LIGAÇÃO COM A EMPRESA SEM UTILIZAR FOREIGN KEY 
);

CREATE TABLE sensor(
    id INT PRIMARY KEY AUTO_INCREMENT,
    posicao_interna VARCHAR(50), -- IDENTIFICAR ONDE ESTÁ O SENSOR(CASO HAJA 2 SENSORES NA MESMA CÂMARA, SABEMOS QUAL ESTÁ LENDO TAL TEMPERATURA/UMIDADE)
    status_ VARCHAR(20) DEFAULT 'ativo' -- STATUS DO SENSOR
    CONSTRAINT chStatus CHECK (status_ IN ('ativo', 'inativo', 'concerto')), -- REGRA PARA CHECAR O INSERT DO STATUS
    id_camara INT -- LIGAÇÃO COM A CAMARA (AQUI VOCÊ DIZ EM QUAL CÂMARA O SENSOR ESTÁ, PODENDO HAVER MAIS DE UM SENSOR POR CÂMARA)
);

CREATE TABLE leitura( 
    id INT PRIMARY KEY AUTO_INCREMENT, 
    temperatura DECIMAL(4,2), -- DADOS DE TEMPERATURA QUE O SENSOR VAI NOS FORNECER
    umidade DECIMAL(4,2), -- DADOS DE UMIDADE QUE O SENSOR VAI NOS FORNECER
    dtRegistros DATETIME DEFAULT CURRENT_TIMESTAMP, -- DATA E HORÁRIO EM QUE OS REGISTROS FORAM COMPUTADOS
    id_sensor INT -- LIGAÇÃO COM O SENSOR QUE FEZ A MEDIÇÃO (SEM USAR FOREIGN KEY)
);

-- (TEMPERATURA IDEAL DAS VACINAS HPV 2°C A 8°C) -- UTILIZAR O APELIDO X°C EM TODOS SELECTS
-- TENTAR FAZER UM SELECT CONCATENANDO OU USANDO OPERAÇÕES ARITMÉTICAS